### ISSUE TITLE
Option to choose no message

### ISSUE THREAD

**Issue by AnandChowdhary** [machine-learning-apps/Issue-Label-Bot#32]
It would be great if users could decide whether they:

1. Want Issue Label Bot to label the issues and post the message with details about confidence, thumbs up, links, etc. (default)
2. Want Issue Label Bot to only label the issue silently without the message

Right now, (1) is default and not optional.

**Comment by hamelsmu** [comment]
@AnandChowdhary thanks for the feedback will put this on my list for when I build version 2
