### ISSUE TITLE
Invalid Workflow File

### ISSUE THREAD

**Issue by danrovito** [machine-learning-apps/Issue-Label-Bot#59]
My runner keeps telling me Invalid Workflow File

Here is what I'm using
https://github.com/Kurbyio/Kurby/blob/1.0/.github/workflows/issue_label_bot.yaml

It looks right to me. Just need a second pair of eyes.

**Comment by hamelsmu** [comment]
@danrovito the problem appears to be your file is in the wrong directory - it should be in `.github/` not `.github/workflows` (the latter is reserved for GitHub Actions), and this project is a GitHub App unrelated to GitHub Actions

**Comment by danrovito** [comment]
Thank you! Silly me!
